service: watch-with-me

provider:
  profile: lesgars-watch-with-me
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: eu-west-3

functions:
  connect:
    handler: handler.connect
    events:
      - websocket:
          route: $connect # authorizers are only for connect routes
          authorizer:
            name: auth
            identitySource:
              - 'route.request.header.Auth'
  default:
    handler: handler.default
    events:
      - websocket:
          route: $default

  auth:
    handler: auth.auth
