service:
  name: watch-with-me

plugins:
  - serverless-iam-roles-per-function # allows to set permissions per function

custom:
  tableName: RoomTable

provider:
  profile: lesgars-watch-with-me
  name: aws
  stage: dev
  runtime: nodejs12.x
  region: eu-west-3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - execute-api:ManageConnections
      Resource:
        - "*"

  environment:
    TABLE_NAME: ${self:custom.tableName}

functions:
  connect:
    handler: handler.connect
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource:
          - "Fn::GetAtt": [RoomTable, Arn]
    events:
      - websocket:
          route: $connect
          # Only if we want authenticated connections
          authorizer:
            name: auth
            identitySource:
              - "route.request.header.Auth"
  disconnect:
    handler: handler.disconnect
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
          - dynamodb:DeleteItem
        Resource:
          - "Fn::GetAtt": [RoomTable, Arn]
    events:
      - websocket:
          route: $disconnect
  read:
    handler: handler.read
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Query
        Resource:
          - "Fn::GetAtt": [RoomTable, Arn]
    events:
      - websocket:
          route: read
  default:
    handler: handler.default
    iamRoleStatementsInherit: true
    events:
      - websocket:
          route: $default
  auth:
    handler: auth.auth

resources:
  - ${file(resources/dynamodb.yml)}
