Resources:
  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.roomTable}
      AttributeDefinitions:
        - AttributeName: roomId
          AttributeType: S
      KeySchema:
        - AttributeName: roomId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
