Resources:
  RoomTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: RoomTable
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
        - AttributeName: uuid
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
        - AttributeName: uuid
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      StreamSpecification:
        StreamViewType: NEW_IMAGE
